version: '3.3'
services:
  apiruby:
    container_name: api-ruby
    image: didox/desafio_multiplasapis_ruby_tarefas:latest
    ports:
      - "8001:3000"
    environment:
      RAILS_ENV: production
      DATABASE: api-ruby
      USER: root
      PASSWORD: root
      HOST: 192.168.0.17

  apinode:
    container_name: api-node
    image: didox/desafio_multiplasapis_nodejs_eventos
    ports:
      - "8002:3000"
    environment:
      DATABASE: api-node
      USER: root
      PASSWORD: root
      HOST: 192.168.0.17